config/routes.rb
Rails.application.routes.draw do

  resources :days

  resources :users

  resources :requests

  resources :users, only: [:show] do
    resources :titles, only: [:new, :create, :index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/facebook/callback', to: 'sessions#create'
  root "application#home"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :requests
  has_many :users, through: :requests

  def self.sorted_days
    order(dayoff: :asc)
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :day

  def day_attributes=(day_hash)
    ymd = "#{day_hash["dayoff(1i)"]}-#{day_hash["dayoff(2i)"]}-#{day_hash["dayoff(3i)"]}"
    self.day = Day.find_or_create_by(:dayoff => ymd)
    self.save
  end
end

app/models/title.rb
class Title < ApplicationRecord
  belongs_to :user
  validates :title_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_many :days, through: :requests
  has_many :titles
  has_secure_password
  validates :username, uniqueness: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

 def current_user
   @current_user ||= User.find_by(id: session[:user_id])
 end

 def logged_in?
   !!current_user
 end

 def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
  end

  def index
    @days = Day.sorted_days
  end

  private
    def day_params
      params.require(:day).permit(:dayoff)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :access_allowed, only: [:edit, :update, :destroy]

  def create
    @user = User.find_by(id: params[:id])
    @request = Request.new(request_params)

    if @request.save
      redirect_to user_path(current_user)
    else
       flash.now[:error] = @request.errors.full_messages
       render :new
    end
  end

  def edit
    @request = Request.find_by(id: params[:id])
  end

  def update
    if @request.update(request_params)
      redirect_to user_path(current_user)
    else
      flash.now[:error] = @request.errors.full_messages
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to user_path(current_user)
  end

  private
    def request_params
      params.require(:request).permit(:user_id, :day_id, :reason, day_attributes:[:dayoff])
    end

    def access_allowed
      @request = Request.find(params[:id])
      if @request.user != current_user
        redirect_to user_path(current_user)
      end
    end
end

app/controllers/sessions_controller.rb
require "simple-password-gen"
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth
        @user = User.find_or_create_by(username: auth["info"]["email"]) do |u|
          u.password = Password.pronounceable 9
        end

        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(current_user)
        end

    else #regular login below

      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(current_user)

      else
        flash.now[:error] = ["There was an error, logging you in, please try again!"]
        render :new
      end
    end
  end

  def destroy
    session.clear
    redirect_to root_url
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def new
    @title = Title.new
  end

  def index
    user = User.find_by(id: params[:user_id])
    @titles = user.titles
  end

  def create
    @user = User.find(params[:user_id])
    @title = Title.new(title_params)
    if @title.save
      redirect_to user_titles_path(@user, @titles)
    else
      render :new
    end
  end

  private

  def title_params
    params.require(:title).permit(:title_name, :user_id, :title_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @request = Request.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<% if !logged_in? %>
  <h1>Please <%= link_to 'login', login_path %>, <%= link_to 'signup', '/users/new' %> or <%= link_to 'login via Facebook', '/auth/facebook' %> to view your days off.</h1>

<% else %>
  <h1>Welcome <%= current_user.username %></h1>

  <h3>Go to <%= link_to 'Office Homepage', days_path %></h3>

  <h3>Log <%= link_to 'days off', user_path(current_user) %></h3>

  <p><%= link_to "Sign out", logout_path, method: :delete %></p>

<% end %>

app/views/days/_form_edit.html.erb
<h1>Please Amend Your Days Off Below</h1>

<%= form_for @request do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.fields_for :day, @request.build_day do |day_field| %>
    <%= day_field.date_select(:dayoff, :order => [:month, :day, :year]) %>
<% end %>
  <%= f.label :reason %>
  <%= f.text_field :reason %>
  <%= f.submit "Edit" %>
<% end %>

<p><%= link_to "Sign out", logout_path, method: :delete %></p>

app/views/days/index.html.erb
<h1>Below Are The Currently Logged Days Off of The Office</h1>
<ul>
<% @days.each do |day| %>
<li> <%= day.dayoff %> </li>
<% end %>
</ul>

<p><%= link_to "Sign out", logout_path, method: :delete %></p>
<h3><%= link_to 'Logged Days', user_path(current_user) %></h3>

app/views/days/new.html.erb
<h1>Please Log Your Days Off Below</h1>

  <%= form_for @day do |f| %>

    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.fields_for :day, @day.build do |day_field| %>
      <%= day_field.date_select(:dayoff, :order => [:month, :day, :year]) %>
  <% end %>
    <%= f.label :reason %>
    <%= f.text_field :reason %>
    <%= f.submit %>
<% end %>

<p><%= link_to "Sign out", logout_path, method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<ul>
<% if flash[:error] %>
  <% flash[:error].each do |message| %>
  <li><%= message %></li>
  <% end %>
<% end %>
</ul>
  <head>
    <title>DaysOffRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= form_for @request do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.fields_for :day, @request.build_day do |day_field| %>
    <%= day_field.date_select(:dayoff, :order => [:month, :day, :year]) %>
<% end %>
  <%= f.label :reason %>
  <%= f.text_field :reason, required: true  %>
  <%= f.submit %>
<% end %>

app/views/requests/edit.html.erb
<h1>Please Amend Your Days Off Below</h1>
<%= render 'requests/form' %>
<h3>Go to <%= link_to 'Office Homepage', days_path %></h3>

<p><%= link_to "Sign out", logout_path, method: :delete %></p>

app/views/titles/index.html.erb
<h1>Your titles are:</h1>
  <ul><% @titles.each do |title| %>
    <li><%= title.title_name %></li>
  <% end %>
  </ul>

  <h3><%= link_to 'Logged Days', user_path(current_user) %></h3>

app/views/titles/new.html.erb
<h1>Please Enter Your Title Here</h1>

<%= form_for :title, :url => url_for(:controller => 'titles', :action => 'create'), method: :post do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :title_name %>
  <%= f.text_field :title_name %>
  <%= f.submit "Add Title" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Below to Log Days Off</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<p><h1>Hi, <%=@user.username%></h1></p>

  <h3>Log Days</h3>

  <%= render 'requests/form' %>

  <ul>
    <% @user.requests.each do |request| %>
  <li><%= request.day.dayoff %>
  <%= request.reason %> <%= link_to "Edit", edit_request_path(request.id) %> <%= link_to "Delete", "/requests/#{request.id}", method: :delete %></li>
<% end %>
</ul>

<p><%= link_to "Add Your Title", "/users/#{current_user.id}/titles/new" %></p>
<p><%= link_to "Sign out", logout_path, method: :delete %></p>